behaviors:
  RobotWalk2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      beta_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 500
    max_steps: 30000000
    time_horizon: 1000
    summary_freq: 50000
    checkpoint_interval: 250000
environment_parameters:
  block_offset:
    curriculum:
      - name: Lesson0 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: RobotWalk2
          signal_smoothing: true
          min_lesson_length: 1
          threshold: 0.1
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: RobotWalk2
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.8
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 2.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: RobotWalk2
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.8
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.5
            max_value: 3.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: RobotWalk2
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.8
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 2.0
            max_value: 5.0
      - name: Lesson4
        value: 5.0

